name: CI

on: [push, pull_request_target]

jobs:
  test:
    name: Tests Trebuchet Action

    steps:
      - name: Trebuchet push
        uses: jhindulak/trebuchet-action@0.0.1
        with:
          action: push
          image: hello/world:3.4-beta
          assume_role_arn: 'arn:aws:iam::112233445566:role/PushToECR'
          profile: 'pe-staging'
          region: 'us-east-1'
          verbose: false

      - name: Trebuchet pull
        with:
          action: pull
          image: hello/world:3.4-beta
          assume_role_arn: 'arn:aws:iam::112233445566:role/PushToECR'
          profile: 'pe-staging'
          region: 'us-east-1'
          verbose: false

      - name: Trebuchet repo
        with:
          action: repository
          image: hello/world:3.4-beta
          assume_role_arn: 'arn:aws:iam::112233445566:role/PushToECR'
          profile: 'pe-staging'
          region: 'us-east-1'
          verbose: false