name: CI

on:
  push:
    branches:
      - main

jobs:
  test-trebuchet-action:
    name: Test Trebuchet Action
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Trebuchet Push
        uses: ./
        id: trebuchet-push
        with:
          action: push
          image: hello/world:3.4-beta
          assumeRoleArn: 'arn:aws:iam::112233445566:role/PushToECR'
          awsProfile: 'pe-staging'
          awsRegion: 'us-east-1'
          verbose: false

      - name: Trebuchet Pull
        uses: ./
        id: trebuchet-pull
        with:
          action: pull
          image: hello/world:3.4-beta
          assumeRoleArn: 'arn:aws:iam::112233445566:role/PushToECR'
          awsProfile: 'pe-staging'
          awsRegion: 'us-east-1'
          verbose: false