name: CI

on:
  push:
    branches:
      - main

jobs:
  test-trebuchet-action:
    name: Test Trebuchet Action
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Trebuchet Test
        uses: ./
        id: trebuchet
        with:
          action: push
          image: hello/world:3.4-beta
          assume_role_arn: 'arn:aws:iam::112233445566:role/PushToECR'
          profile: 'pe-staging'
          region: 'us-east-1'
          verbose: false